stages:
  - release

release-image:
  stage: release
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -t "$CI_REGISTRY_IMAGE/depdetective:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE/depdetective:$CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG

